### ISSUE TITLE
The problem with the development

### ISSUE THREAD

**Issue by Ercogx** [base-cms/base-cms#486]
This is a really cool CMS, but I had a lot of trouble understanding it. I spent the whole day searching for some documentation or maybe some chats in messengers, forums at least something - but nothing.
I have a lot of mistakes, could you help me figure out what to do after `scripts/install.sh`

If I try `scripts/run.sh graphql-server` I got this error

![error graphql-server](https://little-about-web.top/img/1.png)

If I try `scripts/run.sh example-website-bzb` I got 500 Internal Server Error, other "example-site" I have this error too

![error graphql-server](https://little-about-web.top/img/2.png)

I also tried to run `ember serve` in the folder archived/manage but it gives me a strange error.

![error graphql-server](https://little-about-web.top/img/3.png)

**Comment by solocommand** [comment]
Hey @Ercogx! Looks like there are some configuration issues with your installation of Docker/Docker Compose. It looks like you're running on Windows, which hasn't been tested very much!

Rather than using the helper script, try running the Compose command directly:
```
docker-compose run --rm --service-ports graphql-server
```

You may also be able to find additional information using the `log-level` flag:
```
docker-compose --log-level debug run --rm --service-ports graphql-server
```

In your first example, it looks like there's a syntax error.  We'll get that fixed, but the line should read as follows:
```
...(NEW_RELIC_ENABLED ? [() => ApolloNewrelicExtension()] : []),
```

The second issue should be resolved when the first is fixed, as the graphql-server boot error is the cause.

For the third issue, the management service was slated for deletion (under the archived folder) as it was a proof of concept that was never fully built out.

Finally, while this repository/org is called BaseCMS, the actual CMS is proprietary. This repository deals primarily with the building of websites using Marko that use the cms data source. If you'd like to talk about use cases for the CMS, feel free to reach out to sales@parameter1.com -- we'd love to talk!
